### ISSUE TITLE
Move sensor usage methods into a controller/helper

### ISSUE THREAD

**Issue by sionc** [sionc/sager_app#6]
Currently, the usage data is calculated in the model and the as_json method is modified to append these virtual attributes to the json string. We should consider getting rid of these methods from the model and performing these calculations in the controller or helper.

**Comment by sionc** [comment]
A lot of blogs suggest that we go with a "Fat model, skinny controller" strategy. But, we need to do more research about this. If we go with this strategy, then this enhancement need not be impplemented.

**Comment by akurilin** [comment]
I've looked into that as well and it seems to be a highly contentious issue among the community. I think it's reasonable to follow the convention of keeping the controllers as simple as possible and leave most of the business and access logic to the model. How much is too much is up to the developer and his taste: some people feel code smells earlier than others.

If you think a controller method is overly bloated, we can refactor it.

Regarding too much business logic in the models, I've read around and it seems that most people agree that in MVC you are supposed to put all of the business logic into the M, and don't have to feel bad about it. Like many, I thought at first that M was just the data access layer (DAL), but in reality it seems that it's not how it was designed to work.

I think you can eventually refactor some of the code out into modules just so that your model doesn't reach thousands of lines of code (that's a lot of functionality in Ruby!!), but at this point we can get away with everything in one place.
