### ISSUE TITLE
user_sensors route is a duplication

### ISSUE THREAD

**Issue by akurilin** [sionc/sager_app#8]
In app/controllers/pages_controller.rb there's a chunk of code that says:

```
# GET /pages/user_sensors.json
def user_sensors
    @user_sensors = current_user.sensors

    respond_to do |format|
      format.json { render json: {:sensors => @user_sensors} }
    end
  end
```

This is really the job of app/controllers/sensors_controller.rb

```
def index
  @sensors = Sensor.all

  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @sensors }
  end
end
```

Since the sensors index should be restricted to only one user by default,
you can either change that action, or keep this issue open until I add in the
CanCan gem.

My point is that we most likely do not need there two separate actions and
routes for the same operation.

**Comment by sionc** [comment]
That's where I put it first and then I moved it because I thought for initial development, we might need a route to all sensors in the system because we don't have an admin role.

But, ideally, we should modify the sensors index action. 

In summary, I agree and I will make the change in the next commit. When you have CanCan working, we can modify the index action to give the admin access to all sensors in the system.

Sion

**Comment by akurilin** [comment]
It's my opinion that at this point we don't need an admin role. If we need to see the data for the system as a whole, the local rails console (or any other interface to the persisted state, like the postgre console) or the remote heroku console should be sufficient. That is unless we have a very specific need that I'm missing right now.

**Comment by sionc** [comment]
I have deleted the user_sensors action.
See e6642528d389e4ea2e0c2cc3e5b33b03e953fb74
